[WIP] PageNumber support margin top
johnfercher/maroto pull request #502
Opened 2024-12-22 12:51 UTC by zirain

**Description**

add a new filed `MarginTop` in `PageNumber` which help on issues https://github.com/johnfercher/maroto/issues/495

**Related Issue**

https://github.com/johnfercher/maroto/issues/495

**Checklist**
> check with "x", **ONLY IF APPLIED** to your change

- [ ] All methods associated with structs has ```func (<first letter of struct> *struct) method() {}``` name style. 
- [ ] Wrote unit tests for new/changed features. 
- [ ] Followed the unit test ```when,should``` naming pattern. 
- [ ] All mocks created with ```m := mocks.NewConstructor(t)```. 
- [ ] All mocks using ```m.EXPECT().MethodName()``` method to mock methods. 
- [ ] Updated docs/doc.go and docs/* 
- [ ] Updated ```example_test.go```. 
- [ ] Updated README.md 
- [ ] New public methods/structs/interfaces has comments upside them explaining they responsibilities 
- [ ] Executed `make dod` with none issues pointed out by `golangci-lint`

2025-01-06 17:26 UTC, Fernando-hub527 requested changes
Hello, I noticed that there are just a few changes left to finalize the PR, and I believe they won't be very complex:

Currently, when the pageNumber is added to the PDF using the provider.AddText method, the method ensures that the text position does not exceed the cell limits (page dimensions minus margins). While this behavior is necessary in many situations, it prevents the pageNumber from being freely positioned.

To address this, I suggest creating a new AddPageNumber method in the [provider](https://github.com/johnfercher/maroto/blob/master/internal/providers/gofpdf/text.go), similar to [AddText](https://github.com/johnfercher/maroto/blob/master/internal/providers/gofpdf/text.go#L33). However, this method should specifically limit the text position by the page dimensions instead of cell boundaries.

If you need any help implementing this suggestion, I'm happy to assist.

2025-01-06 17:26 UTC, Fernando-hub527 commented on pkg/props/page.go
>  	if p.Place == RightBottom || p.Place == Bottom || p.Place == LeftBottom {
This snippet effectively adjusts the marginTop of the pageNumber when it is positioned at the bottom of the PDF. However, it would be great if similar adjustments could also be made when the pageNumber is at the top of the PDF. Additionally, it would be helpful if the marginLeft could be customizable as well.

2025-01-11 16:04 UTC, Fernando-hub527 approved these changes
The changes were almost correct, but for them to work, the addPageNumber method should bypass the validations made [here](https://github.com/johnfercher/maroto/blob/master/internal/providers/gofpdf/text.go#L33). Instead of creating a new AddPageNumber method, I added a parameter to the addText method that allows you to define whether the text position should respect the page margins or not.

This is result: 
![Captura de tela de 2025-01-11 13-02-12](https://github.com/user-attachments/assets/2f762dc1-4787-466e-bb64-add900a4c1de)

2025-01-12 01:44 UTC, zirain commented
@Fernando-hub527 thanks for the help.

2025-01-13 02:26 UTC, zirain commented
@Fernando-hub527 can we merge this?

2025-01-13 23:09 UTC, Fernando-hub527 commented
> @Fernando-hub527 can we merge this?

Hi, the merge is done by @johnfercher , I believe he will soon be checking the pr

￼

2025-02-14 12:35 UTC, zirain commented
fixed conflict, @Fernando-hub527 can you approve CI again.

2025-02-14 17:35 UTC, johnfercher reviewed
Hey, I added a question. I also have another, it this work with default props? i.e, if someone is using the page number and doesn't set marginTop and marginLeft, it works?

https://maroto.io/#/v2/features/pagenumber?id=page-number

2025-02-14 17:35 UTC, johnfercher commented on pkg/props/page.go
> +	MarginLeft float64
It this the same value that we have inside cfg.Margins? That we compute in builder... If it is, we should pass this in props, because it will get strange...It this is the same margin top, we should get from config...

2025-02-14 17:35 UTC, johnfercher commented on pkg/components/page/page.go
> +		provider.AddPageNumber(p.number, p.total, &p.prop, &cell)
See, if the marginLeft and marginTop are from config, we should use the values from `config *entity.Config` and passing down to provider.

```go
p.config.Margins
```

2025-02-16 12:57 UTC, zirain commented
> Hey, I added a question. I also have another, it this work with default props? i.e, if someone is using the page number and doesn't set marginTop and marginLeft, it works?
> 
> https://maroto.io/#/v2/features/pagenumber?id=page-number

it should work, add a test for it.

2025-02-16 12:59 UTC, zirain commented on pkg/props/page.go
> +	MarginLeft float64
IIUC, pagenumber is a kind of special text, we should not inherit from page config.

the original idea is make footRow and pageNumber work together with better display.

2025-04-03 06:50 UTC, closed without merging